# Generated by Django 4.2 on 2025-07-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('pz', 'Piezas')], max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
