# Generated by Django 4.2 on 2025-07-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_proveedor_remove_materiaprima_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedormateriaprima',
            unique_together=set(),
        ),
    ]
